logging:
    level:
        blog: WARN
        org: WARN
        org.hibernate.SQL: 'off'
spring:
    application:
        name: MobiLeLeLe
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: Himikal30
        url: jdbc:mysql://localhost:3306/MobiLeLeLe?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
